version: '2'

services:
  kong-database:
    image: cassandra:2.2
    ports:
      - 9042:9042
  kong:
    image: kong
    restart: always
    links:
      - kong-database:kong-database
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PG_HOST=kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp

